kind: pipeline
type: docker
name: test and build

steps:

- name: package private repo
  image: registry.nextpertise.tools/nextpertise-proxy/plugins/docker
  privileged: true
  settings:
    repo: registry.nextpertise.tools/nextpertise/dnstool
    registry: registry.nextpertise.tools
    username:
      from_secret: platform_harbor_username
    password:
      from_secret: platform_harbor_password
    tags:
      - latest

- name: package public repo
  image: registry.nextpertise.tools/nextpertise-proxy/plugins/docker
  privileged: true
  settings:
    repo: registry.nextpertise.tools/nextpertise/dnstool
    registry: registry.nextpertise.tools
    username:
      from_secret: registry1_nextpertise_nl_harbor_user
    password:
      from_secret: registry1_nextpertise_nl_harbor_token
    tags:
      - latest

image_pull_secrets:
  - platform_harbor_pull_secrets